// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_db

import (
	"database/sql"
	"time"
)

type Device struct {
	Deviceid         string
	Userid           string
	Publickey        []byte
	Gwip             string
	Publicip         sql.NullString
	Refreshtokenhash string
	Accesstokenhash  string
	Firstaccesstime  time.Time
	Lastaccesstime   time.Time
	Useragent        string
}

type Group struct {
	Groupid   string
	Groupname string
	Groupdesc sql.NullString
}

type GroupDevice struct {
	Groupid  string
	Deviceid string
}

type GroupUser struct {
	Groupid string
	Userid  string
}

type Policy struct {
	Policyid         string
	Policytype       string
	Policyname       string
	Policydesc       sql.NullString
	Sendertype       string
	Senderid         string
	Receivertype     string
	Receiverid       string
	Bidirectional    bool
	Active           bool
	Createdtimestamp time.Time
	Createdby        string
}

type User struct {
	Userid        string
	Username      string
	Usertype      string
	Oauthprovider string
	Oauthid       string
	Isrevoked     bool
}
