// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc_db

import (
	"context"
	"database/sql"
	"time"
)

const addDeviceToGroup = `-- name: AddDeviceToGroup :exec

INSERT INTO group_devices (
    groupId, deviceId
) VALUES (
    ?, ?
)
`

type AddDeviceToGroupParams struct {
	Groupid  string
	Deviceid string
}

// =====================
// | Group <-> Devices |
// =====================
func (q *Queries) AddDeviceToGroup(ctx context.Context, arg AddDeviceToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addDeviceToGroup, arg.Groupid, arg.Deviceid)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec

INSERT INTO group_users (
    groupId, userId
) VALUES (
    ?, ?
)
`

type AddUserToGroupParams struct {
	Groupid string
	Userid  string
}

// ===================
// | Group <-> Users |
// ===================
func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.Groupid, arg.Userid)
	return err
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (
    deviceId, userId, publicKey, gwIp, publicIp, firstAccessTime, lastAccessTime, userAgent, refreshTokenHash, accessTokenHash
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING deviceid, userid, publickey, gwip, publicip, refreshtokenhash, accesstokenhash, firstaccesstime, lastaccesstime, useragent
`

type CreateDeviceParams struct {
	Deviceid         string
	Userid           string
	Publickey        []byte
	Gwip             string
	Publicip         sql.NullString
	Firstaccesstime  time.Time
	Lastaccesstime   time.Time
	Useragent        string
	Refreshtokenhash string
	Accesstokenhash  string
}

// =============
// |  Devices  |
// =============
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.Deviceid,
		arg.Userid,
		arg.Publickey,
		arg.Gwip,
		arg.Publicip,
		arg.Firstaccesstime,
		arg.Lastaccesstime,
		arg.Useragent,
		arg.Refreshtokenhash,
		arg.Accesstokenhash,
	)
	var i Device
	err := row.Scan(
		&i.Deviceid,
		&i.Userid,
		&i.Publickey,
		&i.Gwip,
		&i.Publicip,
		&i.Refreshtokenhash,
		&i.Accesstokenhash,
		&i.Firstaccesstime,
		&i.Lastaccesstime,
		&i.Useragent,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (
    groupId, groupName, groupDesc
) VALUES (
    ?, ?, ?
) RETURNING groupid, groupname, groupdesc
`

type CreateGroupParams struct {
	Groupid   string
	Groupname string
	Groupdesc sql.NullString
}

// ==========
// | Groups |
// ==========
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Groupid, arg.Groupname, arg.Groupdesc)
	var i Group
	err := row.Scan(&i.Groupid, &i.Groupname, &i.Groupdesc)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one

INSERT INTO policies (
    policyType, policyName, policyDesc, senderType, senderId,
    receiverType, receiverId, bidirectional, active, createdTimestamp, createdBy
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING policyid, policytype, policyname, policydesc, sendertype, senderid, receivertype, receiverid, bidirectional, active, createdtimestamp, createdby
`

type CreatePolicyParams struct {
	Policytype       string
	Policyname       string
	Policydesc       sql.NullString
	Sendertype       string
	Senderid         string
	Receivertype     string
	Receiverid       string
	Bidirectional    bool
	Active           bool
	Createdtimestamp time.Time
	Createdby        string
}

// ============
// | Policies |
// ============
func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy,
		arg.Policytype,
		arg.Policyname,
		arg.Policydesc,
		arg.Sendertype,
		arg.Senderid,
		arg.Receivertype,
		arg.Receiverid,
		arg.Bidirectional,
		arg.Active,
		arg.Createdtimestamp,
		arg.Createdby,
	)
	var i Policy
	err := row.Scan(
		&i.Policyid,
		&i.Policytype,
		&i.Policyname,
		&i.Policydesc,
		&i.Sendertype,
		&i.Senderid,
		&i.Receivertype,
		&i.Receiverid,
		&i.Bidirectional,
		&i.Active,
		&i.Createdtimestamp,
		&i.Createdby,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    userId, userName, userType, oAuthProvider, oAuthId, isRevoked
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING userid, username, usertype, oauthprovider, oauthid, isrevoked
`

type CreateUserParams struct {
	Userid        string
	Username      string
	Usertype      string
	Oauthprovider string
	Oauthid       string
	Isrevoked     bool
}

// ===========
// |  Users  |
// ===========
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Userid,
		arg.Username,
		arg.Usertype,
		arg.Oauthprovider,
		arg.Oauthid,
		arg.Isrevoked,
	)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Usertype,
		&i.Oauthprovider,
		&i.Oauthid,
		&i.Isrevoked,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE deviceId = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, deviceid string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, deviceid)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE groupId = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, groupid string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, groupid)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies
WHERE policyId = ?
`

func (q *Queries) DeletePolicy(ctx context.Context, policyid string) error {
	_, err := q.db.ExecContext(ctx, deletePolicy, policyid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE userId = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userid)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT deviceid, userid, publickey, gwip, publicip, refreshtokenhash, accesstokenhash, firstaccesstime, lastaccesstime, useragent FROM devices
WHERE deviceId = ? LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, deviceid string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, deviceid)
	var i Device
	err := row.Scan(
		&i.Deviceid,
		&i.Userid,
		&i.Publickey,
		&i.Gwip,
		&i.Publicip,
		&i.Refreshtokenhash,
		&i.Accesstokenhash,
		&i.Firstaccesstime,
		&i.Lastaccesstime,
		&i.Useragent,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT groupid, groupname, groupdesc FROM groups
WHERE groupId = ? LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, groupid string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, groupid)
	var i Group
	err := row.Scan(&i.Groupid, &i.Groupname, &i.Groupdesc)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT policyid, policytype, policyname, policydesc, sendertype, senderid, receivertype, receiverid, bidirectional, active, createdtimestamp, createdby FROM policies
WHERE policyId = ? LIMIT 1
`

func (q *Queries) GetPolicy(ctx context.Context, policyid string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, policyid)
	var i Policy
	err := row.Scan(
		&i.Policyid,
		&i.Policytype,
		&i.Policyname,
		&i.Policydesc,
		&i.Sendertype,
		&i.Senderid,
		&i.Receivertype,
		&i.Receiverid,
		&i.Bidirectional,
		&i.Active,
		&i.Createdtimestamp,
		&i.Createdby,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT userid, username, usertype, oauthprovider, oauthid, isrevoked FROM users
WHERE userId = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Usertype,
		&i.Oauthprovider,
		&i.Oauthid,
		&i.Isrevoked,
	)
	return i, err
}

const getUsersByUsername = `-- name: GetUsersByUsername :many
SELECT userid, username, usertype, oauthprovider, oauthid, isrevoked FROM users
WHERE userName = ?
ORDER BY userId
`

func (q *Queries) GetUsersByUsername(ctx context.Context, username string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Usertype,
			&i.Oauthprovider,
			&i.Oauthid,
			&i.Isrevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT deviceid, userid, publickey, gwip, publicip, refreshtokenhash, accesstokenhash, firstaccesstime, lastaccesstime, useragent FROM devices
WHERE userId = ?
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userid string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.Deviceid,
			&i.Userid,
			&i.Publickey,
			&i.Gwip,
			&i.Publicip,
			&i.Refreshtokenhash,
			&i.Accesstokenhash,
			&i.Firstaccesstime,
			&i.Lastaccesstime,
			&i.Useragent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesInGroup = `-- name: ListDevicesInGroup :many
SELECT d.deviceId, d.userId, d.publicKey, d.gwIp, d.publicIp, d.firstAccessTime, d.lastAccessTime, d.userAgent, d.refreshTokenHash, d.accessTokenHash
FROM devices d
JOIN group_devices gd ON d.deviceId = gd.deviceId
WHERE gd.groupId = ?1
UNION
SELECT d.deviceId, d.userId, d.publicKey, d.gwIp, d.publicIp, d.firstAccessTime, d.lastAccessTime, d.userAgent, d.refreshTokenHash, d.accessTokenHash
FROM devices d
JOIN group_users gu ON d.userId = gu.userId
WHERE gu.groupId = ?1
`

type ListDevicesInGroupRow struct {
	Deviceid         string
	Userid           string
	Publickey        []byte
	Gwip             string
	Publicip         sql.NullString
	Firstaccesstime  time.Time
	Lastaccesstime   time.Time
	Useragent        string
	Refreshtokenhash string
	Accesstokenhash  string
}

// For the union logic of devices and user's devices
func (q *Queries) ListDevicesInGroup(ctx context.Context, groupid string) ([]ListDevicesInGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesInGroup, groupid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesInGroupRow
	for rows.Next() {
		var i ListDevicesInGroupRow
		if err := rows.Scan(
			&i.Deviceid,
			&i.Userid,
			&i.Publickey,
			&i.Gwip,
			&i.Publicip,
			&i.Firstaccesstime,
			&i.Lastaccesstime,
			&i.Useragent,
			&i.Refreshtokenhash,
			&i.Accesstokenhash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.groupid, g.groupname, g.groupdesc FROM groups g
JOIN group_users gu ON g.groupId = gu.groupId
WHERE gu.userId = ?
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userid string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Groupid, &i.Groupname, &i.Groupdesc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlyDevicesInGroup = `-- name: ListOnlyDevicesInGroup :many
SELECT d.deviceid, d.userid, d.publickey, d.gwip, d.publicip, d.refreshtokenhash, d.accesstokenhash, d.firstaccesstime, d.lastaccesstime, d.useragent FROM devices d
JOIN group_devices gd ON d.deviceId = gd.deviceId
WHERE gd.groupId = ?
`

func (q *Queries) ListOnlyDevicesInGroup(ctx context.Context, groupid string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listOnlyDevicesInGroup, groupid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.Deviceid,
			&i.Userid,
			&i.Publickey,
			&i.Gwip,
			&i.Publicip,
			&i.Refreshtokenhash,
			&i.Accesstokenhash,
			&i.Firstaccesstime,
			&i.Lastaccesstime,
			&i.Useragent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT policyid, policytype, policyname, policydesc, sendertype, senderid, receivertype, receiverid, bidirectional, active, createdtimestamp, createdby FROM policies
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.Policyid,
			&i.Policytype,
			&i.Policyname,
			&i.Policydesc,
			&i.Sendertype,
			&i.Senderid,
			&i.Receivertype,
			&i.Receiverid,
			&i.Bidirectional,
			&i.Active,
			&i.Createdtimestamp,
			&i.Createdby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT userid, username, usertype, oauthprovider, oauthid, isrevoked FROM users
ORDER BY userId
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Usertype,
			&i.Oauthprovider,
			&i.Oauthid,
			&i.Isrevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInGroup = `-- name: ListUsersInGroup :many
SELECT u.userid, u.username, u.usertype, u.oauthprovider, u.oauthid, u.isrevoked FROM users u
JOIN group_users gu ON u.userId = gu.userId
WHERE gu.groupId = ?
`

func (q *Queries) ListUsersInGroup(ctx context.Context, groupid string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersInGroup, groupid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Username,
			&i.Usertype,
			&i.Oauthprovider,
			&i.Oauthid,
			&i.Isrevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDeviceFromGroup = `-- name: RemoveDeviceFromGroup :exec
DELETE FROM group_devices
WHERE groupId = ? AND deviceId = ?
`

type RemoveDeviceFromGroupParams struct {
	Groupid  string
	Deviceid string
}

func (q *Queries) RemoveDeviceFromGroup(ctx context.Context, arg RemoveDeviceFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeDeviceFromGroup, arg.Groupid, arg.Deviceid)
	return err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM group_users
WHERE groupId = ? AND userId = ?
`

type RemoveUserFromGroupParams struct {
	Groupid string
	Userid  string
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.Groupid, arg.Userid)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET publicKey = ?, gwIp = ?, publicIp = ?, firstAccessTime = ?, lastAccessTime = ?, userAgent = ?, refreshTokenHash = ?, accessTokenHash = ?
WHERE deviceId = ?
RETURNING deviceid, userid, publickey, gwip, publicip, refreshtokenhash, accesstokenhash, firstaccesstime, lastaccesstime, useragent
`

type UpdateDeviceParams struct {
	Publickey        []byte
	Gwip             string
	Publicip         sql.NullString
	Firstaccesstime  time.Time
	Lastaccesstime   time.Time
	Useragent        string
	Refreshtokenhash string
	Accesstokenhash  string
	Deviceid         string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevice,
		arg.Publickey,
		arg.Gwip,
		arg.Publicip,
		arg.Firstaccesstime,
		arg.Lastaccesstime,
		arg.Useragent,
		arg.Refreshtokenhash,
		arg.Accesstokenhash,
		arg.Deviceid,
	)
	var i Device
	err := row.Scan(
		&i.Deviceid,
		&i.Userid,
		&i.Publickey,
		&i.Gwip,
		&i.Publicip,
		&i.Refreshtokenhash,
		&i.Accesstokenhash,
		&i.Firstaccesstime,
		&i.Lastaccesstime,
		&i.Useragent,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET groupName = ?, groupDesc = ?
WHERE groupId = ?
RETURNING groupid, groupname, groupdesc
`

type UpdateGroupParams struct {
	Groupname string
	Groupdesc sql.NullString
	Groupid   string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.Groupname, arg.Groupdesc, arg.Groupid)
	var i Group
	err := row.Scan(&i.Groupid, &i.Groupname, &i.Groupdesc)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET policyType = ?, policyName = ?, policyDesc = ?, senderType = ?, senderId = ?, receiverType = ?, receiverId = ?, bidirectional = ?, active = ?
WHERE policyId = ?
RETURNING policyid, policytype, policyname, policydesc, sendertype, senderid, receivertype, receiverid, bidirectional, active, createdtimestamp, createdby
`

type UpdatePolicyParams struct {
	Policytype    string
	Policyname    string
	Policydesc    sql.NullString
	Sendertype    string
	Senderid      string
	Receivertype  string
	Receiverid    string
	Bidirectional bool
	Active        bool
	Policyid      string
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, updatePolicy,
		arg.Policytype,
		arg.Policyname,
		arg.Policydesc,
		arg.Sendertype,
		arg.Senderid,
		arg.Receivertype,
		arg.Receiverid,
		arg.Bidirectional,
		arg.Active,
		arg.Policyid,
	)
	var i Policy
	err := row.Scan(
		&i.Policyid,
		&i.Policytype,
		&i.Policyname,
		&i.Policydesc,
		&i.Sendertype,
		&i.Senderid,
		&i.Receivertype,
		&i.Receiverid,
		&i.Bidirectional,
		&i.Active,
		&i.Createdtimestamp,
		&i.Createdby,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET userName = ?, userType = ?, oAuthProvider = ?, oAuthId = ?, isRevoked = ?
WHERE userId = ?
`

type UpdateUserParams struct {
	Username      string
	Usertype      string
	Oauthprovider string
	Oauthid       string
	Isrevoked     bool
	Userid        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Usertype,
		arg.Oauthprovider,
		arg.Oauthid,
		arg.Isrevoked,
		arg.Userid,
	)
	return err
}
